package com.bitgear.skiguard.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bitgear.skiguard.dao.User;
import com.bitgear.skiguard.dao.History;
import com.bitgear.skiguard.dao.Device;

import com.bitgear.skiguard.dao.UserDao;
import com.bitgear.skiguard.dao.HistoryDao;
import com.bitgear.skiguard.dao.DeviceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig historyDaoConfig;
    private final DaoConfig deviceDaoConfig;

    private final UserDao userDao;
    private final HistoryDao historyDao;
    private final DeviceDao deviceDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        historyDaoConfig = daoConfigMap.get(HistoryDao.class).clone();
        historyDaoConfig.initIdentityScope(type);

        deviceDaoConfig = daoConfigMap.get(DeviceDao.class).clone();
        deviceDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        historyDao = new HistoryDao(historyDaoConfig, this);
        deviceDao = new DeviceDao(deviceDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(History.class, historyDao);
        registerDao(Device.class, deviceDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        historyDaoConfig.clearIdentityScope();
        deviceDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public HistoryDao getHistoryDao() {
        return historyDao;
    }

    public DeviceDao getDeviceDao() {
        return deviceDao;
    }

}
