package com.bitgear.skiguard.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "HISTORY".
 */
@Entity
public class History {

    @Id(autoincrement = true)
    private Long id;
    private int id_device;
    private Float lat;
    private Float lng;
    private Integer battery;
    private Integer id_track;
    private Integer id_track_change;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public History() {
    }

    public History(Long id) {
        this.id = id;
    }

    @Generated
    public History(Long id, int id_device, Float lat, Float lng, Integer battery, Integer id_track, Integer id_track_change) {
        this.id = id;
        this.id_device = id_device;
        this.lat = lat;
        this.lng = lng;
        this.battery = battery;
        this.id_track = id_track;
        this.id_track_change = id_track_change;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getId_device() {
        return id_device;
    }

    public void setId_device(int id_device) {
        this.id_device = id_device;
    }

    public Float getLat() {
        return lat;
    }

    public void setLat(Float lat) {
        this.lat = lat;
    }

    public Float getLng() {
        return lng;
    }

    public void setLng(Float lng) {
        this.lng = lng;
    }

    public Integer getBattery() {
        return battery;
    }

    public void setBattery(Integer battery) {
        this.battery = battery;
    }

    public Integer getId_track() {
        return id_track;
    }

    public void setId_track(Integer id_track) {
        this.id_track = id_track;
    }

    public Integer getId_track_change() {
        return id_track_change;
    }

    public void setId_track_change(Integer id_track_change) {
        this.id_track_change = id_track_change;
    }

    // KEEP METHODS - put your custom methods here

    // KEEP METHODS END

}
