package com.bitgear.skiguard.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "HISTORY".
 */
@Entity
public class History {

    @Id(autoincrement = true)
    private Long id;
    private int id_device;
    private float lat;
    private float lng;
    private int battery;
    private int id_track;

    @Unique
    private int id_track_change;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public History() {
    }

    public History(Long id) {
        this.id = id;
    }

    @Generated
    public History(Long id, int id_device, float lat, float lng, int battery, int id_track, int id_track_change) {
        this.id = id;
        this.id_device = id_device;
        this.lat = lat;
        this.lng = lng;
        this.battery = battery;
        this.id_track = id_track;
        this.id_track_change = id_track_change;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getId_device() {
        return id_device;
    }

    public void setId_device(int id_device) {
        this.id_device = id_device;
    }

    public float getLat() {
        return lat;
    }

    public void setLat(float lat) {
        this.lat = lat;
    }

    public float getLng() {
        return lng;
    }

    public void setLng(float lng) {
        this.lng = lng;
    }

    public int getBattery() {
        return battery;
    }

    public void setBattery(int battery) {
        this.battery = battery;
    }

    public int getId_track() {
        return id_track;
    }

    public void setId_track(int id_track) {
        this.id_track = id_track;
    }

    public int getId_track_change() {
        return id_track_change;
    }

    public void setId_track_change(int id_track_change) {
        this.id_track_change = id_track_change;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        History history = (History) o;

        return getId_track_change() == history.getId_track_change();

    }

    @Override
    public int hashCode() {
        return getId_track_change();
    }
    // KEEP METHODS END

}
