package com.bitgear.skiguard.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "LIFT".
 */
@Entity
public class Lift {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String name;

    @NotNull
    private String boundary;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Lift() {
    }

    public Lift(Long id) {
        this.id = id;
    }

    @Generated
    public Lift(Long id, String name, String boundary) {
        this.id = id;
        this.name = name;
        this.boundary = boundary;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    @NotNull
    public String getBoundary() {
        return boundary;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBoundary(@NotNull String boundary) {
        this.boundary = boundary;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
